# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-12 18:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_auto_20160713_0026'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Total',
        ),
    ]
