# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-18 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_storeuserans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeuserans',
            name='subans',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
