# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-18 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_auto_20160719_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeuserans',
            name='ques_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
